name: 'dbt_projeto_um'
version: '1.0.0'

profile: 'dbt_projeto_um'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:     
  - "target"
  - "dbt_packages"


models:
  dbt_projeto_um:
    staging:
      schema: staging
      +materialized: table
      tags: "[staging]"
    
    intermediate:
      +materialized: ephemeral
      tags: "[intermediate]"

    marts:
      schema: marts
      +materialized: table
      tags: "[marts]"

seeds:
  dbt_example:
    +schema: seeds
    tags: "[seeds]"